Navigation Menu and Bottom Surrouding Button Menu
Soundscape-Project-UCL/Soundscape pull request #49
Opened 2024-01-17 12:44 UTC by FriedhelmWS

Please notice the content in this PR is not perfect (i.e. fully done done, some magic numbers and some sizing things still need to improve), want to get the basic functionalities in so that we can incrementally improve later on.

Include the drawer menu, custom app bar, basic colours (from IOS app) and bottom surrounding button menu. The basic functionalities are included.

Home:
![image](https://github.com/Soundscape-Project-UCL/Soundscape/assets/67029085/385b1f8c-0f39-4ff4-89a1-3e7550723ff6)

Drawer Menu:
![image](https://github.com/Soundscape-Project-UCL/Soundscape/assets/67029085/24f5de81-732f-41f0-96e8-e4d54a6a3428)

Issue: #32

2024-01-17 12:47 UTC, FriedhelmWS commented on app/src/main/res/values/colors.xml
> +    <color name="foreground3">#b3ecff</color>
Borrowed from IOS assets, need to review once we have the up-to-date design docs

2024-01-17 12:50 UTC, FriedhelmWS commented on app/src/main/res/menu/surrounding_menu.xml
> +        android:visible="false" />
The workaround is to unselect any of the items on the navigation menu.

This is because the bottom menu reuses the built-in BottomNavigationView which reduces the effort of writing a custom menu list. However, there do exist some small style problems as we are not actually "navigating" the use of it.

Happy to discuss if someone feels it is inappropriate.

2024-01-17 12:52 UTC, FriedhelmWS commented on app/src/main/res/layout/activity_main.xml
> +            android:text="Back"
This should be a back icon button.

Will adress once (if) we have the up-to-date design docs, as the back button isn't there in the old design.

2024-01-17 12:57 UTC, FlickerSoul commented
LGTM!

2024-01-17 13:05 UTC, FlickerSoul requested changes
See comments regarding i18n and hard coded strings. The rest looks good :)

2024-01-17 13:05 UTC, FlickerSoul commented on app/src/main/java/org/soundscape/MainActivity.kt
> +                }
The hard coded strings can be replaced with those in `string.xml`.

2024-01-17 13:05 UTC, FlickerSoul commented on app/src/main/res/values/strings.xml
> +    <string name="button_nearby_markers">Nearby\nMarkers</string>
The line breaks (`\n`) shouldn't be added in the internationalizations, and should be added in the UI implementations instead. I'm not a pro in i18n so correct me if I'm wrong.

2024-01-17 13:23 UTC, FriedhelmWS commented on app/src/main/java/org/soundscape/MainActivity.kt
> +                }
These toasts are only a temporal placeholder to indicate where to put the method, these will be replaced with actual functionalities for these buttons.

2024-01-18 23:38 UTC, closed without merging

2024-01-18 23:38 UTC, FriedhelmWS commented
No longer valid since migrate to Jetpack Compose