Sensor manager dispatch data to subscribers
Soundscape-Project-UCL/Soundscape pull request #65
Opened 2024-02-03 18:02 UTC by Luming-Li

### Main features:

- Collect location data and device heading data, then send them every 10 seconds
- Any other component that wants to get sensor data can subscribe to receive update

**How to subscribe:**
```
// Subscribe and log out both location and heading data
// Make sure subscribe to correct data class
        private lateinit var locationSubscriberJob: Job
        private lateinit var headingSubscriberJob: Job

        ...

        locationSubscriberJob = EventBus.global.subscribe<SoundScapeEvent.GeoEvent.LocationChanged> 
        {
                val location = it.location
                Log.d("EventBusData", "Latitude: ${location.latitude}; Longitude: ${location.longitude}; " +"Course Heading: ${location.bearing}; ")
        }

        headingSubscriberJob = EventBus.global.subscribe<SoundScapeEvent.GeoEvent.HeadingChanged> 
        {
            val heading = it.heading
            Log.d("EventBusData", "Device Heading: $heading")
        }

// Unsubscribe if not use
        locationSubscriberJob.cancel()
        headingSubscriberJob.cancel()
```

LocationChanged event provides a location object containing latitude, longitude, coarse heading
HeadingChanged event provides a double number to indicate the device heading
Both headings are in the form of 0-360° (0° pointing at North)

2024-02-04 01:33 UTC, FriedhelmWS approved these changes
Overall LGTM, just a few minor questions

2024-02-04 01:33 UTC, FriedhelmWS commented on app/src/main/java/org/soundscape/events/EventManager.kt
> +        private const val replaySize = 0
Minor: maybe add "_" to the variable name so that the naming convention is consistent?

2024-02-04 01:33 UTC, FriedhelmWS commented on app/src/main/java/org/soundscape/MainActivity.kt
> +        val serviceSensorManagerIntent = Intent(this, SensorManagerService::class.java)
Just for curiosity, why do we need to refer as Java class even though it is  Kotlin

2024-02-04 01:33 UTC, FriedhelmWS commented on app/src/main/java/org/soundscape/events/Events.kt
> +sealed class SoundScapeEvent {
Minor: "Soundscape"

2024-02-04 01:33 UTC, FriedhelmWS commented on app/src/main/java/org/soundscape/service/HeadingService.kt
> +            if(it.type == "heading"){
Is that good to use enum here?

2024-02-04 01:33 UTC, FriedhelmWS commented on app/src/main/java/org/soundscape/service/LocationService.kt
> +            }, 1000) // Delay 1s, wait until subscriber created
Do we have to hardcoded a time interval for waiting? Is there a way to actually "wait until" something is ready?

2024-02-04 22:07 UTC, anisahn09 commented on app/src/main/java/org/soundscape/events/EventManager.kt
> +        private const val replaySize = 0
updated

2024-02-04 22:07 UTC, anisahn09 commented on app/src/main/java/org/soundscape/MainActivity.kt
> +        val serviceSensorManagerIntent = Intent(this, SensorManagerService::class.java)
quoting from [stackoverflow](https://stackoverflow.com/questions/39462397/intents-in-kotlin):

> Its because you are calling Java Code from the Kotlin as Intent is a Java Class in Android which accepts .class reference as mentioned below. Intent(Context packageContext, Class cls) Kotlin class reference is not the same as a Java class reference.

2024-02-04 22:07 UTC, anisahn09 commented on app/src/main/java/org/soundscape/events/Events.kt
> +sealed class SoundScapeEvent {
updated

2024-02-04 22:07 UTC, anisahn09 commented on app/src/main/java/org/soundscape/service/HeadingService.kt
> +            if(it.type == "heading"){
updated to use enum

2024-02-05 01:40 UTC, FlickerSoul requested changes

2024-02-05 01:40 UTC, FlickerSoul commented on app/src/main/java/org/soundscape/events/EventManager.kt
The event manager is defined in the core package. What's the reason for redefining it again?

2024-02-05 01:40 UTC, FlickerSoul commented on app/src/main/java/org/soundscape/events/EventManager.kt
Oh I see. The audio-dev isn't merged so the core package isn't present in your current structure. Could you try merge the audio-dev first?

2024-02-05 01:40 UTC, FlickerSoul commented on app/src/main/java/org/soundscape/service/LocationService.kt
> +            }, 1000) // Delay 1s, wait until subscriber created
I would advise not using event bus for this purpose, namely listening to permission change. This event only occurs when users change their permissions which is very rare. 

Just call the corresponding callback would be the best, I think.

2024-02-05 01:40 UTC, FlickerSoul commented on app/src/main/java/org/soundscape/service/HeadingService.kt
> +            if(it.type == "heading"){
Agree, enum would be the best for `type` :)

2024-02-05 01:45 UTC, FlickerSoul requested changes

2024-02-05 01:45 UTC, FlickerSoul commented on app/src/main/java/org/soundscape/service/ServiceEnum.kt
> +enum class ServiceEnum(val type: String) {
Why does each enum item carry a String `type`? It would be sufficient without the associated data, namely 

```kotlin
enum class HeadingServiceType {  // could use a more descriptive name
    HEADING,
    LOCATION
}
```

2024-02-05 17:42 UTC, anisahn09 commented on app/src/main/java/org/soundscape/events/EventManager.kt
If we merge the audio-dev, it will be also merged to main. Is it okay?

2024-02-05 23:28 UTC, dragonfist453 commented on app/src/main/java/org/soundscape/events/EventManager.kt
@FlickerSoul I guess you guys can raise an MR with decently stable changes?

2024-02-06 10:21 UTC, dragonfist453 requested changes

2024-02-06 10:21 UTC, dragonfist453 commented on app/src/main/java/org/soundscape/service/SensorManagerService.kt
Although I agree with this code as it aims to combine, I see a few concerns with this:

1. In this way, you would be "ignoring" or dropping a few events because they are irrelevant either on the location or heading side because of the waiting that is done through the conditions for the other event. This is not a good practice because it leads to loss of information. What would be good is to combine the latest results of either of them, and emit an LocationHeadingUpdated event. 

The difference can be demonstrated with this image showing what happens when there is a combineLatest:

![image](https://github.com/Soundscape-Project-UCL/Soundscape/assets/48686287/c263937c-660e-468c-bced-b70d00439618)

With combineLatest, the b3 would be acknowledged and emitted without waiting for c, but in the way it is currently written, we would ignore the event 3, and only emit c4, which may not be good.

2. We can surely make the person using this decide whether they only want Location or Heading or both. When they need both, they can take care to merge them together themselves. Emitting the LocationChanged in LocationService and HeadingChanged in HeadingService, and optionally also an event with both could be nice, but it's good to give the programmer the liberty to choose the event instead of delivering it together with control in this way!

2024-02-06 10:21 UTC, dragonfist453 commented on app/src/main/java/org/soundscape/events/EventManager.kt
Let's wait for audio-dev to get merged with these components, so that we can use their files instead of adding these files here

2024-02-06 10:24 UTC, dragonfist453 commented on app/src/main/java/org/soundscape/service/SensorManagerService.kt
However, the code is really good and I just want it to work in this way for it to be very useful for all of us working with it. Thanks a lot!

2024-02-06 10:47 UTC, dragonfist453 commented on app/src/main/java/org/soundscape/events/EventManager.kt
> +    inline fun <reified T : SoundscapeEvent> subscribe(crossinline onEvent: (T) -> Unit): Job {
@FlickerSoul So... I agree with the event being subscribed to here as a Job, but I think more control should be given to the developer by just providing the Flow with filter. Right now, the developer can't really control much besides doing a subscribe which I am sure is great, but having control is good as we can use the EventBus freely in the place where events are subscribed and emitted.

2024-02-06 11:56 UTC, dragonfist453 commented on app/src/main/java/org/soundscape/service/SensorManagerService.kt
Sorry to spam, but to add to point 1, there is a bigger issue. If for some reason, we aren't getting location events, heading events will also stop and get blocked, and vice-versa. That is the critical issue with this approach.

2024-02-06 11:57 UTC, dragonfist453 commented on app/src/main/java/org/soundscape/events/EventManager.kt
> +    inline fun <reified T : SoundscapeEvent> subscribe(crossinline onEvent: (T) -> Unit): Job {
Essentially, we can either change this to just return the filtered Flow for the developer to figure out how they want to use it, or add a new method returning the filtered Flow and this method to stay if the developer wants just the data. It can be used as needed.

2024-02-06 13:43 UTC, FlickerSoul commented on app/src/main/java/org/soundscape/events/EventManager.kt
> +    inline fun <reified T : SoundscapeEvent> subscribe(crossinline onEvent: (T) -> Unit): Job {
Yes I agree with you. More control should be given to the developers. What do you think adding several often-used parameters to `subscribe`? Since flow is exposed, developers can always create their own filter or add an extension to the existing class.

2024-02-06 13:44 UTC, FlickerSoul commented on app/src/main/java/org/soundscape/events/EventManager.kt
A separate events package is merged. Mark as resolved.

2024-02-06 14:45 UTC, dragonfist453 commented on app/src/main/java/org/soundscape/events/EventManager.kt
> +    inline fun <reified T : SoundscapeEvent> subscribe(crossinline onEvent: (T) -> Unit): Job {
You can add often-used parameters but for now, having a function that simply exposes the Flow object for that event type should be enough. Developers can further add more functionality when they see the need to.

2024-02-06 14:52 UTC, dragonfist453 commented on core/events/src/main/java/org/soundscape/events/EventManager.kt
> +            flow.debounce(debounceMs).filterIsInstance<T>().collect {
Do we need the debounce for our application? Any specific reason?

2024-02-06 17:10 UTC, FlickerSoul commented on core/events/src/main/java/org/soundscape/events/EventManager.kt
> +            flow.debounce(debounceMs).filterIsInstance<T>().collect {
No I meant to add throttle. So we can have a way to limit rates.

2024-02-06 18:05 UTC, anisahn09 commented on app/src/main/java/org/soundscape/service/LocationService.kt
> +            }, 1000) // Delay 1s, wait until subscriber created
updated, now it uses livedata for permission checking. kindly review it again, thankss!

2024-02-06 18:33 UTC, FlickerSoul commented on app/src/main/java/org/soundscape/service/SensorManagerService.kt
> +            if (locationIntentReceived && headingIntentReceived) sendLocationAndHeadingData()
What's the reason for the location and heading data to be sent at the same time? Sending them from the heading service and location service should be sufficient, I think?

2024-02-06 18:47 UTC, FlickerSoul commented
I removed the `SensorManagerService` because we don't need the heading and location changes to be sent at the same time. If the need comes up, we revert the delete and implement a better sync mechanism as mentioned by @dragonfist453

2024-02-06 18:48 UTC, dragonfist453 commented on app/src/main/java/org/soundscape/service/SensorManagerService.kt
> +            if (locationIntentReceived && headingIntentReceived) sendLocationAndHeadingData()
It really should be, and besides suggesting the right way to send these events together, my comment was that these can be used separately. The events can be merged together when needed to, and used instead. With the flow exposed for us to use, we can do all the flow based operations to work with them conveniently!

2024-02-06 18:56 UTC, dragonfist453 approved these changes
Fantastic work! Looks brilliant and much better than earlier, even though it was already good then!

@FriedhelmWS Can you have a look and see if this works for your future use-cases as well?

2024-02-06 19:10 UTC, FlickerSoul approved these changes
Great work! Thank you guys!

2024-02-06 20:15 UTC, merged